### ISSUE TITLE
06-Kata Week 06

### ISSUE THREAD

**Issue by ta-datapt-bcn** [ironhack-bcn-data-pt/katas-challenge#7]
Esta semana dos katas, la de la semana y una de REGEX como prometí:

**SEMANA**
https://www.codewars.com/kata/56f253dd75e340ff670002ac

**REGEX** (hacedla con regex, se puede hacer sin, pero entonces no tiene sentido)
https://www.codewars.com/kata/56a921fa8c5167d8e7000053/train/python

como siempre podéis hacer una o las dos

**Comment by aGimenezO** [comment]
REgex:
https://www.codewars.com/kata/reviews/5d7906a2a4b23f0001b6ea92/groups/5f1efe8d354fd600011abf49

**Comment by cucu-o0** [comment]
regex
https://www.codewars.com/kata/reviews/5d7906a2a4b23f0001b6ea92/groups/5f1f0cc059b8bf00018ca2b0

**Comment by cucu-o0** [comment]
regex
https://www.codewars.com/kata/reviews/5d7906a2a4b23f0001b6ea92/groups/5f1f11500032450001005964

**Comment by LolaLop** [comment]
regex:
https://www.codewars.com/kata/reviews/5d7906a2a4b23f0001b6ea92/groups/5f201542cf3ee00001497486

**Comment by LolaLop** [comment]
Semana:
https://www.codewars.com/kata/reviews/56f254a479a48cce0500002b/groups/5f2032bd5d3a030001fe2c2a

**Comment by cucu-o0** [comment]
semana:
https://www.codewars.com/kata/reviews/56f254a479a48cce0500002b/groups/5f46aaf469f1cd0001cfe14c
