### ISSUE TITLE
07-Kata Week 07

### ISSUE THREAD

**Issue by ta-datapt-bcn** [ironhack-bcn-data-pt/katas-challenge#8]
Una kata facilita para las vacaciones
https://www.codewars.com/kata/561bbcb0fbbfb0f5010000ee

**Comment by aGimenezO** [comment]
https://www.codewars.com/kata/reviews/561cc88a0ccf620085000029/groups/5f2a9eb5da3cee000121c524

**Comment by LolaLop** [comment]
https://www.codewars.com/kata/reviews/561cc88a0ccf620085000029/groups/5f33b36592a0ec0001518fce
